# ============================================
# MCPサーバーの設定ファイル
# name: Cloudflare Workersでの識別名（変更してください）
# ============================================
name = "japan-holiday-mcp"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]
account_id = "166bb123f41e16dfca50c0874bc43cde"

[observability]
enabled = true

[durable_objects]
bindings = [
  { name = "MCP_OBJECT", class_name = "JapanHolidayMcpAgent" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["JapanHolidayMcpAgent"]
